/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import App.Proyecto.Controlador.Interface.InterfaceUsuarioDAO;
import App.Proyecto.DAO.UsuarioDAO;
import App.Proyecto.Modelo.Funciones;
import App.Proyecto.Modelo.Usuario;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin-ronald.arrieta
 */
public class CRUD_Usuario extends javax.swing.JFrame {

    InterfaceUsuarioDAO usu = new UsuarioDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    Funciones Fun = new Funciones();
    public static String nom_usuario;
    public static String nom_persona;

    /**
     * Creates new form CRUD_Usuario
     */
    public CRUD_Usuario() {
        initComponents();
        pintarLabel("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        modelo.addColumn("Id Persona");
        modelo.addColumn("Persona");
        modelo.addColumn("Id Usuario");
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Activo?");
        modelo.addColumn("Fecha Vencimiento");
        modelo.addColumn("Tipo Usuario");
        tblUsuarios.setModel(modelo);
        ListarUsuario();
    }

    public void ListarUsuario() {
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        List<Usuario> p = usu.Listar_Usuarios();
        for (int i = 0; i < p.size(); i++) {
            String Estado_Usuario = null;
            String Fecha_Vencimiento = null;
            String Li_tipo_Persona = null;
            Usuario us = new Usuario();
            us = (Usuario) p.get(i);
            if (us.getEstado_Usuario() != null) {
                switch (us.getEstado_Usuario()) {
                    case "1":
                        Estado_Usuario = "ACTIVADO";
                        break;
                    case "0":
                        Estado_Usuario = "DESACTIVADO";
                        break;
                }
            } else {
                Estado_Usuario = "No registrado";
            }
            if (us.getFe_Vencimiento() != null) {
                Fecha_Vencimiento = us.getFe_Vencimiento();
            } else {
                Fecha_Vencimiento = "Sin Limite";
            }
            if (us.getLi_tipo_persona() != null) {
                switch (us.getLi_tipo_persona()) {
                    case "1":
                        Li_tipo_Persona = "Alumno";
                        break;
                    case "2":
                        Li_tipo_Persona = "Docente";
                        break;
                    case "3":
                        Li_tipo_Persona = "Director";
                        break;
                }
            } else {
                Fecha_Vencimiento = "No registrado";
            }
            model.addRow(new Object[]{us.getId_persona(), us.getPersona(), us.getId_Usuario(), us.getNombre_Usuario(), us.getPassword(), Estado_Usuario, Fecha_Vencimiento, Li_tipo_Persona});
        }
        tblUsuarios.setModel(model);

    }

    public void pintarLabel(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 104, 179));
        jLabel2.setText("REGISTRO USAURIOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 230, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "null", "Title 3", "null", "Title 5"
            }
        ));
        tblUsuarios.setGridColor(new java.awt.Color(0, 0, 0));
        tblUsuarios.setSelectionBackground(new java.awt.Color(154, 211, 243));
        jScrollPane1.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 510, 360));

        btnInsertar.setBackground(new java.awt.Color(60, 134, 203));
        btnInsertar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(193, 236, 253));
        btnInsertar.setText("INSERTAR");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 40));

        btnModificar.setBackground(new java.awt.Color(60, 134, 203));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(193, 236, 253));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 40));

        btnAtras.setBackground(new java.awt.Color(60, 134, 203));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(193, 236, 253));
        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 104, 179));
        jLabel4.setText("USUARIOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 80, 20));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Usuario_Form();
        frame.setTitle("Registrar Usuarios");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Principal_Administrador();
        frame.setTitle("MENU");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Principal_Administrador.lblUsuario.setText(nom_usuario);
        Principal_Administrador.lblPersona.setText(nom_persona);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int nro = tblUsuarios.getSelectedColumnCount();
        if (nro > 0) {
            int fila = tblUsuarios.getSelectedRow();
            JFrame frame = new Usuario_Form();
            frame.setTitle("Modificar Usuario");
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
            frame.setVisible(true);
            Usuario_Form.lbltitle.setText("Modificar Usuario");
            Usuario_Form.btnRegistrarUsuario.setText("Modificar");
            Usuario_Form.id_Persona = Integer.parseInt((String) tblUsuarios.getValueAt(fila, 0));
            Usuario_Form.id_Usuario = Integer.parseInt((String) tblUsuarios.getValueAt(fila, 2));
            Usuario_Form.txtPersona.setText((String) tblUsuarios.getValueAt(fila, 1));
            Usuario_Form.txtUsuario.setText((String) tblUsuarios.getValueAt(fila, 3));
            Usuario_Form.txtPassword.setText((String) tblUsuarios.getValueAt(fila, 4));
            Usuario_Form.txtPasswordRe.setText((String) tblUsuarios.getValueAt(fila, 4));
            switch ((String) tblUsuarios.getValueAt(fila, 5)) {
                case "ACTIVADO":
                    Usuario_Form.cmbEstado_Usuario.setSelectedItem("ACTIVADO");
                    break;
                case "DESACTIVADO":
                    Usuario_Form.cmbEstado_Usuario.setSelectedItem("DESACTIVADO");
                    break;
                case "":
                    Usuario_Form.cmbEstado_Usuario.setSelectedItem("--");
                    break;

            }
            if (tblUsuarios.getValueAt(fila, 6).toString().equals("Sin Limite")) {
                Usuario_Form.txtFecha_Vencimiento.setDate(null);
            } else {
                Usuario_Form.txtFecha_Vencimiento.setDate(Fun.Cambiar_Fecha((String) tblUsuarios.getValueAt(fila, 6)));
            }
            Usuario_Form.MenSeleccionar.setEnabled(false);

        }

    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
