/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import App.Proyecto.Controlador.Interface.InterfaceSeccionDAO;
import App.Proyecto.DAO.SeccionDAO;
import App.Proyecto.Modelo.Seccion;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Seccion extends javax.swing.JFrame {

    /**
     * Creates new form Form_Seccion
     */
    String Estado_Seccion;
    public static int id_seccion;
    InterfaceSeccionDAO sec = new SeccionDAO();

    public Form_Seccion() {
        initComponents();
        pintarLabel("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        pintarLabel("src/App/Proyecto/Imagenes/barra.jpg", imgBarraTitulo);
        CargarCombo();

        cmbEstadoSeccion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox comboBox = (JComboBox) e.getSource();
                String valor = (String) comboBox.getSelectedItem();
                switch (valor) {
                    case "ACTIVO":
                        Estado_Seccion = "1";
                        break;
                    case "INACTIVO":
                        Estado_Seccion = "0";
                        break;
                    case "--":
                        Estado_Seccion = "";
                        break;
                }
            }

        });
    }

    public void CargarCombo() {
        DefaultComboBoxModel modelito = new DefaultComboBoxModel();
        modelito.addElement("--");
        modelito.addElement("ACTIVO");
        modelito.addElement("INACTIVO");
        cmbEstadoSeccion.setModel(modelito);
    }

    public void pintarLabel(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void ListarSeccion(JTable Seccion) {
        DefaultTableModel model = (DefaultTableModel) Seccion.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        List<Seccion> p = sec.Listar_Seccion();
        for (int i = 0; i < p.size(); i++) {
            String Est_Seccion = null;
            Seccion s = new Seccion();
            s = (Seccion) p.get(i);
            if (s.getEstado_Seccion().equals("1")) {
                Est_Seccion = "Activado";
            } else if (s.getEstado_Seccion().equals("0")) {
                Est_Seccion = "Desactivado";
            }
            model.addRow(new Object[]{s.getId_seccion(), s.getNombre_Seccion(), Est_Seccion});
        }
        Seccion.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JTextField();
        imgBarraTitulo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbEstadoSeccion = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnRegistrarSeccion = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registrar Seccion");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        txtSeccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeccionActionPerformed(evt);
            }
        });
        txtSeccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));

        imgBarraTitulo.setBackground(new java.awt.Color(0, 0, 0));
        imgBarraTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imgBarraTitulo.setName(""); // NOI18N
        getContentPane().add(imgBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 390, 40));

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Seccion");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 60, 20));

        cmbEstadoSeccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbEstadoSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 100, 30));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Estado Seccion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, 20));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(102, 153, 255));
        btnAtras.setText("Atras");
        btnAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 40));

        btnRegistrarSeccion.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarSeccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarSeccion.setForeground(new java.awt.Color(102, 153, 255));
        btnRegistrarSeccion.setText("Registrar");
        btnRegistrarSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSeccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, 40));

        imgFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtSeccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeccionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtSeccion.getText().length() == 1) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSeccionKeyTyped

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSeccionActionPerformed
        // TODO add your handling code here:
        switch (btnRegistrarSeccion.getText()) {
            case "Registrar":
                if (!txtSeccion.getText().equals("") && !Estado_Seccion.equals("")) {
                    sec.Insertar_Seccion(txtSeccion.getText(), Estado_Seccion);
                    this.dispose();
                    ListarSeccion(Crud_Grado_Seccion.tblSeccion);
                } else {
                    JOptionPane.showMessageDialog(null, "Ingresar datos completos");
                }
                break;
            case "Modificar":
                if (!txtSeccion.getText().equals("") && !Estado_Seccion.equals("")) {
                    sec.Modificar_Seccion(id_seccion, txtSeccion.getText(), Estado_Seccion);
                    this.dispose();
                    ListarSeccion(Crud_Grado_Seccion.tblSeccion);
                } else {
                    JOptionPane.showMessageDialog(null, "Ingresar datos completos");
                }
                break;
        }
    }//GEN-LAST:event_btnRegistrarSeccionActionPerformed

    private void txtSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    public static javax.swing.JButton btnRegistrarSeccion;
    public static javax.swing.JComboBox cmbEstadoSeccion;
    private javax.swing.JLabel imgBarraTitulo;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel lblTitulo;
    public static javax.swing.JTextField txtSeccion;
    // End of variables declaration//GEN-END:variables
}
