/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import App.Proyecto.Controlador.Interface.InterfaceUsuarioDAO;
import App.Proyecto.DAO.UsuarioDAO;
import App.Proyecto.Factory.conexion;
import App.Proyecto.Modelo.Usuario;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Barrantes Tapia
 */
public class Login extends javax.swing.JFrame {

    conexion con;

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        //setSize(450, 300);

        pintar("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        pintar("src/App/Proyecto/Imagenes/usu.png", imgusu);

    }

    public Login(JLabel imgFondo, JLabel imgLapiz, JLabel imgLibros) {
        this.imgFondo = imgFondo;
        this.imgLapiz = imgLapiz;
        this.imgLibros = imgLibros;
    }

    public void pintar(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLibros = new javax.swing.JLabel();
        lblLogueo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        imgLapiz = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        imgusu = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(432, 420));
        setMinimumSize(new java.awt.Dimension(432, 420));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(432, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(imgLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 80, 70));

        lblLogueo.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        lblLogueo.setForeground(new java.awt.Color(29, 104, 179));
        lblLogueo.setText("LOGUEO");
        getContentPane().add(lblLogueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(29, 104, 179));
        lblUsuario.setText("USUARIO");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(29, 104, 179));
        lblContraseña.setText("CONTRASEÑA");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(225, 248, 255));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 153, 255));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 30));
        getContentPane().add(imgLapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        btnIngresar.setBackground(new java.awt.Color(60, 134, 203));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(193, 236, 253));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 40));

        btnSalir.setBackground(new java.awt.Color(60, 134, 203));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(193, 236, 253));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 110, 40));
        getContentPane().add(imgusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 160));

        txtContraseña.setBackground(new java.awt.Color(225, 248, 255));
        txtContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(51, 153, 255));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 170, 30));

        imgFondo.setBackground(new java.awt.Color(255, 255, 255));
        imgFondo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if (!txtUsuario.getText().equals("") && !txtContraseña.getText().equals("")) {
            String Nombre_Usuario;
            String Persona;
            String li_tipo_persona;
            InterfaceUsuarioDAO usu = new UsuarioDAO();
            List<Usuario> u = usu.logueo(txtUsuario.getText().trim(), txtContraseña.getText().trim());
            if (u.size() > 0) {
                Usuario user = new Usuario();
                user = (Usuario) u.get(0);
                Nombre_Usuario = user.getNombre_Usuario();
                if (user.getPersona() != null) {
                    Persona = user.getPersona();
                } else {
                    Persona = "Es nulo";
                }
                li_tipo_persona = user.getLi_tipo_persona();
                switch (user.getEstado_Usuario()) {
                    case "0": {
                        JOptionPane.showMessageDialog(null, "El Usuario:" + Nombre_Usuario + " esta DESACTIVADO");
                    }
                    case "1": {
                        if (user.getEstado_Abierto() != null) {
                            if (user.getEstado_Abierto().equals("1")) {
                                switch (li_tipo_persona.trim()) {
                                    case "3": {
                                        JFrame frame = new Principal_Administrador();
                                        Principal_Administrador.lblPersona.setText(Persona);
                                        Principal_Administrador.lblUsuario.setText(Nombre_Usuario);
                                        frame.setTitle("MENU");
                                        frame.setLocationRelativeTo(null);
                                        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                                        this.dispose();
                                        frame.setVisible(true);
                                        break;
                                    }
                                    case "2": {
                                        JFrame frame = new PrincipalProfesor();
                                        PrincipalProfesor.lblPersona.setText(Persona);
                                        PrincipalProfesor.lblUsuario.setText(Nombre_Usuario);
                                        frame.setTitle("MENU");
                                        frame.setLocationRelativeTo(null);
                                        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                                        this.dispose();
                                        frame.setVisible(true);
                                        break;
                                    }
                                }
                            } else if (user.getEstado_Abierto().equals("0")) {
                                JOptionPane.showMessageDialog(null, "Se vencio la fecha limite de activacion del Usuario:" + Nombre_Usuario);
                                txtContraseña.setText("");
                            }
                        } else if (user.getEstado_Abierto() == null) {
                            switch (li_tipo_persona.trim()) {
                                case "3": {
                                    JFrame frame = new Principal_Administrador();
                                    Principal_Administrador.lblPersona.setText(Persona);
                                    Principal_Administrador.lblUsuario.setText(Nombre_Usuario);
                                    frame.setTitle("MENU");
                                    frame.setLocationRelativeTo(null);
                                    frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                                    this.dispose();
                                    frame.setVisible(true);
                                    break;
                                }
                                case "2": {
                                    JFrame frame = new PrincipalProfesor();
                                    PrincipalProfesor.lblPersona.setText(Persona);
                                    PrincipalProfesor.lblUsuario.setText(Nombre_Usuario);
                                    frame.setTitle("MENU");
                                    frame.setLocationRelativeTo(null);
                                    frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                                    this.dispose();
                                    frame.setVisible(true);
                                    break;
                                }
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Usuario o contraseña incorrecta");
                txtContraseña.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Usuario y Contraseña");
            txtContraseña.setText("");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btnIngresarActionPerformed(null);
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel imgLapiz;
    private javax.swing.JLabel imgLibros;
    private javax.swing.JLabel imgusu;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblLogueo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
