/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package App.Proyecto.Form;

import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Menu_RegistroNotas extends javax.swing.JFrame {

    /**
     * Creates new form Menu_RegistroNotas
     */
    public Menu_RegistroNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        imgBarraTitulo = new javax.swing.JLabel();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnRegistrarProfesor = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblPersona.setText("Persona");
        getContentPane().add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 240, -1));
        getContentPane().add(imgBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 30));

        btnRegistrarAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarAlumno.setText("<html><p>Registrar Notas</p><p>Por Alumno</p></html>");
        btnRegistrarAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarAlumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarAlumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 120));

        btnRegistrarProfesor.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarProfesor.setText("Registrar Profesor");
        btnRegistrarProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarProfesor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarProfesor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 120, 120));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new RegistroAlumnos();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JLabel imgBarraTitulo;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lblPersona;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
