/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class Principal_Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Reportes
     */
    public Principal_Reportes() {
        initComponents();
        pintar("src/App/Proyecto/Imagenes/icono_reportes.png", btnReporteAlumno);
        pintar("src/App/Proyecto/Imagenes/icono_reportes.png", btnReporteNotas);
        pintar("src/App/Proyecto/Imagenes/icono_reportes.png", btnReporteProfesor);
        pintaratras("src/App/Proyecto/Imagenes/ATRAS.png", btnAtras);
        pintarLabel("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        pintarLabel("src/App/Proyecto/Imagenes/barra.jpg", imgBarraTitulo);
    }

    public void pintarLabel(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void pintaratras(String url, JButton obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth()-10, obj.getHeight()-10, Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void pintar(String url, JButton obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth() - 10, obj.getHeight() - 30, Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporteNotas = new javax.swing.JButton();
        btnReporteAlumno = new javax.swing.JButton();
        btnReporteProfesor = new javax.swing.JButton();
        lblPersona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        imgBarraTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporteNotas.setBackground(new java.awt.Color(108, 141, 169));
        btnReporteNotas.setText("Reporte Notas");
        btnReporteNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteNotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReporteNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteNotasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 120, 120));

        btnReporteAlumno.setBackground(new java.awt.Color(108, 141, 169));
        btnReporteAlumno.setText("Reporte Alumnos");
        btnReporteAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteAlumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReporteAlumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, 120));

        btnReporteProfesor.setBackground(new java.awt.Color(108, 141, 169));
        btnReporteProfesor.setText("Reporte Profesor");
        btnReporteProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteProfesor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReporteProfesor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, 120));

        lblPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblPersona.setText("Persona");
        getContentPane().add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 240, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));
        getContentPane().add(imgBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Menu Reportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btnAtras.setBackground(new java.awt.Color(85, 90, 96));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, 50));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteNotasActionPerformed

    private void btnReporteAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAlumnoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Reportes();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Reportes.nom_usuario=lblUsuario.getText();
        Reportes.nom_persona=lblPersona.getText();
    }//GEN-LAST:event_btnReporteAlumnoActionPerformed

    private void btnReporteProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteProfesorActionPerformed
        // TODO add your handling code here:
        /*this.dispose();
         JFrame frame = new FormMatricula();
         frame.setLocationRelativeTo(null);
         frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
         frame.setVisible(true);*/

    }//GEN-LAST:event_btnReporteProfesorActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Principal_Administrador();
        frame.setTitle("MENU");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnReporteAlumno;
    private javax.swing.JButton btnReporteNotas;
    private javax.swing.JButton btnReporteProfesor;
    private javax.swing.JLabel imgBarraTitulo;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel lblPersona;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
