/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import App.Proyecto.Modelo.Funciones;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class PrincipalProfesor extends javax.swing.JFrame {

    Funciones fun = new Funciones();

    /**
     * Creates new form PrincipalProfesor
     */
    public PrincipalProfesor() {
        initComponents();
        pintar("src/App/Proyecto/Imagenes/alumno_logo.png", btnRegistrarAlumno);
        pintar("src/App/Proyecto/Imagenes/Profesor.png", btnRegistrarProfesor);
        pintar("src/App/Proyecto/Imagenes/Matricula.png", btnMatricularAlumno);
        pintar("src/App/Proyecto/Imagenes/Materia_Icono.png", btnRegistrarGadoSeccion);
        pintar("src/App/Proyecto/Imagenes/calificacion.png", btnRegistrarCalificacion);
        pintar("src/App/Proyecto/Imagenes/rep.png", btnReportes);
        pintar("src/App/Proyecto/Imagenes/cursos.png", btnRegistrarMateria);
        pintar("src/App/Proyecto/Imagenes/notas.png", btnRegistrarNotas);
        pintar("src/App/Proyecto/Imagenes/usuarios.png", btnRegistrarUsuarios);
        pintarLabel("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        pintarLabel("src/App/Proyecto/Imagenes/barra.jpg", imgBarraTitulo);
    }

    public void pintarLabel(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void pintar(String url, JButton obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth() - 30, obj.getHeight() - 40, Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPersona = new javax.swing.JLabel();
        imgBarraTitulo = new javax.swing.JLabel();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnRegistrarProfesor = new javax.swing.JButton();
        btnMatricularAlumno = new javax.swing.JButton();
        btnRegistrarGadoSeccion = new javax.swing.JButton();
        btnRegistrarMateria = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnRegistrarNotas = new javax.swing.JButton();
        btnRegistrarUsuarios = new javax.swing.JButton();
        btnRegistrarCalificacion = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblPersona.setText("Persona");
        getContentPane().add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 260, -1));
        getContentPane().add(imgBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, 30));

        btnRegistrarAlumno.setText("Registrar Alumno");
        btnRegistrarAlumno.setToolTipText("Formulario Alumno");
        btnRegistrarAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarAlumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarAlumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 120));

        btnRegistrarProfesor.setText("Registrar Profesor");
        btnRegistrarProfesor.setToolTipText("Formulario Profesor");
        btnRegistrarProfesor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarProfesor.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarProfesor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, 120));

        btnMatricularAlumno.setText("Matricular Alumno");
        btnMatricularAlumno.setToolTipText("Formulario Matricula");
        btnMatricularAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatricularAlumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMatricularAlumno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMatricularAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatricularAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 120, 120));

        btnRegistrarGadoSeccion.setText("Registrar Grado Seccion");
        btnRegistrarGadoSeccion.setToolTipText("Formulario Grado Seccion");
        btnRegistrarGadoSeccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarGadoSeccion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarGadoSeccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarGadoSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGadoSeccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarGadoSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 120, 120));

        btnRegistrarMateria.setText("Registrar Materia");
        btnRegistrarMateria.setToolTipText("Formulario Materia");
        btnRegistrarMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarMateria.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarMateria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 120, 120));

        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("Menu de reportes");
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 120, 120));

        btnRegistrarNotas.setText("Registrar Notas");
        btnRegistrarNotas.setToolTipText("Formulario Notas");
        btnRegistrarNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarNotas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNotasActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, 120));

        btnRegistrarUsuarios.setText("Ingresar Usuarios");
        btnRegistrarUsuarios.setToolTipText("Formulario Usuarios");
        btnRegistrarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarUsuarios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 120, 120));

        btnRegistrarCalificacion.setText("Registrar Calificacion");
        btnRegistrarCalificacion.setToolTipText("Registrar Calificacion");
        btnRegistrarCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarCalificacion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarCalificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnRegistrarCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 120));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new RegistroAlumnos();
        frame.setTitle("Registro Alumnos");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        RegistroAlumnos.nom_usuario = lblUsuario.getText();
        RegistroAlumnos.nom_persona = lblPersona.getText();
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegistrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarProfesorActionPerformed

    private void btnMatricularAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularAlumnoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new FormMatricula();
        frame.setTitle("Matricular alumno");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        FormMatricula.nom_usuario = lblUsuario.getText();
        FormMatricula.nom_persona = lblPersona.getText();

    }//GEN-LAST:event_btnMatricularAlumnoActionPerformed

    private void btnRegistrarGadoSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGadoSeccionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Crud_Grado_Seccion();
        frame.setTitle("Formulario Grado Seccion");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Crud_Grado_Seccion.nom_usuario = lblUsuario.getText();
        Crud_Grado_Seccion.nom_persona = lblPersona.getText();

    }//GEN-LAST:event_btnRegistrarGadoSeccionActionPerformed

    private void btnRegistrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMateriaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new CRUD_Materia();
        frame.setTitle("Formulario Grado Seccion");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        CRUD_Materia.nom_usuario = lblUsuario.getText();
        CRUD_Materia.nom_persona = lblPersona.getText();
    }//GEN-LAST:event_btnRegistrarMateriaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Principal_Reportes();
        frame.setTitle("Menu Reportes");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Principal_Reportes.lblUsuario.setText(lblUsuario.getText());
        Principal_Reportes.lblPersona.setText(lblPersona.getText());
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRegistrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new Registro_Notas();
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        Registro_Notas.nom_persona = lblPersona.getText();
        Registro_Notas.nom_usuario = lblUsuario.getText();
    }//GEN-LAST:event_btnRegistrarNotasActionPerformed

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new CRUD_Usuario();
        frame.setTitle("Formulario Usuarios");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        CRUD_Usuario.nom_usuario = lblUsuario.getText();
        CRUD_Usuario.nom_persona = lblPersona.getText();
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricularAlumno;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegistrarCalificacion;
    private javax.swing.JButton btnRegistrarGadoSeccion;
    private javax.swing.JButton btnRegistrarMateria;
    private javax.swing.JButton btnRegistrarNotas;
    private javax.swing.JButton btnRegistrarProfesor;
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel imgBarraTitulo;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lblPersona;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
