/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App.Proyecto.Form;

import App.Proyecto.Controlador.Interface.InterfacePersonaDAO;
import App.Proyecto.DAO.CellRenderer;
import App.Proyecto.DAO.PersonaDAO;
import App.Proyecto.Factory.conexion;
import App.Proyecto.Modelo.Persona;
import java.awt.Image;
import java.util.Enumeration;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin-ronald.arrieta
 */
public class Selec_Alumno extends javax.swing.JFrame {

    InterfacePersonaDAO al = new PersonaDAO();
    conexion con;
    DefaultTableModel modelo = new DefaultTableModel();

    public class ModeloTabla extends DefaultTableModel {

        public boolean isCellEditable(int row, int col) {
            if (col == 0) {
                return false;
            } else {
                return true;
            }
        }
    }
    ModeloTabla modo = new ModeloTabla();

    /**
     * Creates new form Selec_Alumno
     */
    public Selec_Alumno() {
        initComponents();
        pintarLabel("src/App/Proyecto/Imagenes/fondo_celeste.jpg", imgFondo);
        pintarLabel("src/App/Proyecto/Imagenes/barra.jpg", imgBarraTitulo1);
        modo.addColumn("Id_Persona");
        modo.addColumn("Nombres");
        modo.addColumn("Apellido Paterno");
        modo.addColumn("Apellido Materno");
        modo.addColumn("DNI");
        modo.addColumn("Estado Alumno");
        jTListaAlumno.setModel(modo);
        ListarAlumno();
        setCellRender(jTListaAlumno);
    }

    public void setCellRender(JTable table) {
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
        }
    }

    public void pintarLabel(String url, JLabel obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth(), obj.getHeight(), Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void pintar(String url, JButton obj) {
        ImageIcon imagen = new ImageIcon(url);
        Icon Icono = new ImageIcon(imagen.getImage().getScaledInstance(obj.getWidth() - 30, obj.getHeight() - 80, Image.SCALE_DEFAULT));
        obj.setIcon(Icono);
        this.repaint();
    }

    public void ListarAlumno() {
        DefaultTableModel modelo = (DefaultTableModel) jTListaAlumno.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        TableColumnModel modCol = jTListaAlumno.getColumnModel();
        Object[][] row = {};
        List<Persona> p = al.ListarAlumno();
        for (int i = 0; i < p.size(); i++) {
            String Estado_Persona = null;
            Persona per = new Persona();
            per = (Persona) p.get(i);
            if (per.getEstado_Alumno() == null) {
                Estado_Persona = "No Matriculado";
            } else if (per.getEstado_Alumno().equals("1")) {
                Estado_Persona = "No Matriculado";
            } else if (per.getEstado_Alumno().equals("2")) {
                Estado_Persona = "Matriculado";
            }
            modelo.addRow(new Object[]{per.getId_Persona(), per.getNombre_Persona(), per.getApellido_Paterno(), per.getApellido_Materno(), per.getDni(), Estado_Persona});
        }
        jTListaAlumno.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTListaAlumno = new javax.swing.JTable();
        IngresarDatos1 = new javax.swing.JLabel();
        imgBarraTitulo1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        btnATRAS = new javax.swing.JButton();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(666, 488));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTListaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTListaAlumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 620, 330));

        IngresarDatos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IngresarDatos1.setForeground(new java.awt.Color(255, 255, 255));
        IngresarDatos1.setText("Seleccionar Alumno");
        getContentPane().add(IngresarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        imgBarraTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        imgBarraTitulo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imgBarraTitulo1.setName(""); // NOI18N
        getContentPane().add(imgBarraTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 660, 40));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(102, 153, 255));
        btnSeleccionar.setText("Enviar");
        btnSeleccionar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 120, 30));

        btnATRAS.setBackground(new java.awt.Color(255, 255, 255));
        btnATRAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnATRAS.setForeground(new java.awt.Color(102, 153, 255));
        btnATRAS.setText("ATRAS");
        btnATRAS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATRASActionPerformed(evt);
            }
        });
        getContentPane().add(btnATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 120, 30));

        imgFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int count = jTListaAlumno.getSelectedRowCount();
        if (count > 0) {
            int fila;
            fila = jTListaAlumno.getSelectedRow();
            int id_persona;
            String cod_estudiante;
            id_persona = (int) jTListaAlumno.getValueAt(fila, 0);
            List<Persona> list = al.ListarAlumnoxId(id_persona);
            if (list.size() > 0) {
                Persona per = new Persona();
                per = (Persona) list.get(0);
                if (per.getCod_Estudiante() != null) {
                    cod_estudiante = per.getCod_Estudiante();
                } else {
                    cod_estudiante = "Falta Ingresar";
                }
                FormMatricula.txtAlumno.setText(cod_estudiante + " : " + per.getNombre_Persona() + " " + per.getApellido_Paterno() + " " + per.getApellido_Materno());
                FormMatricula.id_persona = per.getId_Persona();
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccinar una fila de la tabla");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATRASActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnATRASActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IngresarDatos1;
    public javax.swing.JButton btnATRAS;
    public javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel imgBarraTitulo1;
    private javax.swing.JLabel imgFondo;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListaAlumno;
    // End of variables declaration//GEN-END:variables
}
